apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: flask-app
spec:
  template:
    metadata:
      name: 'flask-app-{{cluster}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/lexops/infra'
        path: kustomize/overlays/{{cluster}}
        targetRevision: HEAD
      destination:
        server: {{cluster}}
        namespace: {{cluster}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
      - cluster: hml
        url: https://kubernetes.default.svc
      - cluster: prod
        url: https://kubernetes.default.svc