apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deploy
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: flask-app
        image: lexops/flask-app:latest
        ports:
        - name: flask
          containerPort: 5000