name: Add Tenant
on:
  workflow_dispatch:
    inputs:
      tenant:
        description: 'Nome do cliente a ser adicionado'
        required: true
env:
  TENANT: ${{ github.event.inputs.tenant }}
jobs:
  Add-Tenant:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create tenant dirs
      run: cp -r kustomize/overlays/dev kustomize/overlays/$TENANT
    - name: Update  new tenant namespace
      uses: mikefarah/yq@master
      with:
        cmd: |
          yq -ie '.namespace = env(TENANT)' kustomize/overlays/$TENANT/kustomization.yml
    - name: Add new tenant dirs to ArgoCD ApplicationSet
      uses: mikefarah/yq@master
      with:
        cmd: |
          yq -ie  '.spec.generators[0].list.elements += [{"env": env(TENANT)}]' argocd/applicationset.yml  
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v5.0.0
