name: Create Cluster
run-name: 🚀 Subindo o cluster
on:
  workflow_dispatch:
env:
  TF_VAR_access_key: ${{ secrets.ARM_CLIENT_SECRET }}
jobs:
  Add-Cluster:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: terraform
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: hashicorp/setup-terraform@v3
    # - name: Terraform fmt
    #   id: fmt
    #   run: terraform fmt -check
    #   continue-on-error: true
    - name: Terraform Init
      id: init
      run: terraform init
    # - name: Terraform Validate
    #   id: validate
    #   run: terraform validate -no-color
    # - name: Terraform Plan
    #   id: plan
    #   run: terraform plan -no-color
    #   continue-on-error: true
    # - name: Git Auto Commit
    #   uses: stefanzweifel/git-auto-commit-action@v5.0.0
