name: Create Cluster
run-name: 🚀 Criando cluser
on:
  workflow_dispatch:
env:
  ARM_ACCESS_KEY: ${{ secrets.TF_VAR_ACCESS_KEY }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.TF_VAR_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.TF_VAR_TENANT_ID}}
  ARM_CLIENT_ID: ${{ secrets.TF_VAR_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.TF_VAR_CLIENT_SECRET }}
jobs:
  Create-Cluster:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write
    defaults:
      run:
        working-directory: terraform
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Replace Terraform Backend Config vars 
      run: envsubst < backend.conf > backend.conf
    - run: cat backend.conf
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
    # - name: Terraform fmt
    #   id: fmt
    #   run: terraform fmt -check
    #   continue-on-error: true
    - run: rm -rf .terraform
    - name: Terraform Init
      id: init
      run: terraform init -backend-config=backend.conf
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true
