name: Deploy to Dev
on:
  workflow_dispatch:
jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v2.1.0-rc
    - name: Update Image
      working-directory: kustomize/overlays/dev
      run: |
        kustomize edit set image lexops/flask-app:${GITHUB_RUN_NUMBER}
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Set `lexops/flask-app` image tag to `${{ github.run_number }}`
